### ISSUE TITLE
AFE control standarization

### ISSUE THREAD

**Issue by gkasprow** [sinara-hw/AFE_DAC_External#1]
Can we make a uniform pinout of each AFE connector?
I'm implementing same mini SAS pinout in Fastino-DIOT.
And now, in the Shuttler, the pinout looks in the following way

0 CSN0
1 SCLK
2 MOSI0
3 CSN1
4 MISO0
5.MISO1
6.
7.
8. SCLK2
9. MOSI2
10. CSN2
11. IO
12 MISO2
13 IO
14
15

the idea is to have the same signalling in every mSAS connector.
So I'd suggest swapping some lines in the second connector  so they are compatible with the first connector
AFE CTRL

0 CSN0
1 SCLK01
2 MOSI01
3 CSN1
4 MISO0
5.MISO1
6 GPIO - ID
7 GPIO - ID

8 CSN2
9 SCLK23
10 MOSI23
11 CSN3
12 MISO2
13 MISO3
14 GPIO -ID
15 GPIO - ID

lines 6/14 and 7/15 could be used as connector IDs where AFE pulls them up or down with resistors.

**Comment by maciejprzybysz** [comment]
@gkasprow 
I updated AFE control signals as described. Could you take a look on SCH? I used P3V3 for AFE0_CTRL_14/15 instead of P3V3A - it's easier to route signals and keep P3V3A clean.

> lines 6/14 and 7/15 could be used as connector IDs where AFE pulls them up or down with resistors.

How should I set variant for this pullup/pulldown resistors?

**Comment by gkasprow** [comment]
looks good

> How should I set variant for this pullup/pulldown resistors?

set revision 1. 1 -> ID 0 = up, iD1=down

**Comment by maciejprzybysz** [comment]
And ID2->0, ID3->0 or ID2->1, ID3->0?
![image](https://github.com/user-attachments/assets/001a0715-abb3-40fc-a641-647f4128e81c)

@gkasprow

**Comment by gkasprow** [comment]
yes

**Comment by kaolpr** [comment]
@maciejprzybysz Is it implemented in v1.3rc1?

**Comment by maciejprzybysz** [comment]
yes

**Comment by occheung** [comment]
Besides the newly added 10k pull-up/down to specify the ID on AFE, there is a 2k2 pull-up (to 3.3V) on shuttler for these ID signals when translating from 3.3V to 1.8V. A final voltage around 2.7 V should be expected for ID bits with 10k pull-down.

![Image](https://github.com/user-attachments/assets/d7acb9d0-3305-4709-9a5e-222b6d8df173)

The bus transceiver has this specification on detecting high-level or low-level input.

![Image](https://github.com/user-attachments/assets/01be7ab4-8994-47ba-aa33-4b3ee5005e6e)

The expected voltage is above the threshold (2V), the ID becomes all 1.
